version: '3.7'

services:

  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cluster-network
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
   
  baribank:
    image: baribank:latest
    container_name: baribank
    build:
      context: .
      dockerfile: HostedService/Dockerfile
    depends_on:
      - rabbitmq

networks:
  cluster-network:
    driver: bridge